### ISSUE TITLE
Ajuda

### ISSUE THREAD

**Issue by mvclaudianobj** [Mekylei-Belchior/lotofacil#1]
Posso ajudar em algo? Vc tem resultados de ganhos com esse projeto ?

**Comment by Mekylei-Belchior** [comment]
Olá @mvclaudianobj, tudo bem? Peço desculpa pela demora no retorno. Meu principal objetivo com este projeto era aprender um pouco de Redes Neurais. Não cheguei a utilizá-lo para ganhos financeiros. Para tal, o projeto precisa de mais aprimoramentos!

Acredito que seria interessante desenvolver uma solução para a análise do ciclo das dezenas, que até então é feito numa planilha em Excel. Vamos desenvolver?

**Comment by leandrojgama** [comment]
Olá! sou um estudante de Ciência da computação, me entenreço por data Sicente. Baixei o seu projeto para testar, verifiquei que os  arquivos  csv e XlS não esão disponiveis.

**Comment by Mekylei-Belchior** [comment]
@leandrojgama Boa noite!
O .xls está no diretório `lotofacil/base/`. Já o .csv, é só rodar o código `lotofacil/dados/scrapping_resultados.py` que o mesmo será gerando automaticamente.

**Comment by ithallufernando** [comment]
Boa tarde,
Gostei muito do seu projeto e baixei para estudar mas ao executar no Pycharm me deparei com o seguinte erro:

**_Traceback (most recent call last):
  File "C:\Users\italo.fernando\lotofacil\jogar.py", line 37, in <module>
    possibilidades_atualizada: object = remover_resultado_concursos(
  File "C:\Users\italo.fernando\lotofacil\processamento\reajustar_dados.py", line 18, in remover_resultado_concursos
    indices = [buscar(possibilidades, elem_ini, elem_fin, valor_busca
  File "C:\Users\italo.fernando\lotofacil\processamento\reajustar_dados.py", line 18, in <listcomp>
    indices = [buscar(possibilidades, elem_ini, elem_fin, valor_busca
  File "C:\Users\italo.fernando\lotofacil\dados\busca.py", line 17, in buscar
    if valor_busca > lista[meio]:
TypeError: '>' not supported between instances of 'int' and 'str'_**

Será que poderia me ajudar? @Mekylei-Belchior

**Comment by Mekylei-Belchior** [comment]
Olá @ithallufernando, tudo bem?
Pelo que vi na mensagem, está ocorrendo uma exceção ao tentar comparar tipos de dados diferentes. Não era para acontecer! Tentei replicar o erro  na minha máquina, porém o código rodou normalmente. Tente realizar o passo a passo do link a seguir: 
[Passo a passo](https://github.com/Mekylei-Belchior/lotofacil/issues/2#issuecomment-830655217)  

![tela-power_shell](https://user-images.githubusercontent.com/18305560/122237489-bf4ee600-ce95-11eb-86a6-187a36100438.png)  

![tela-pycharm](https://user-images.githubusercontent.com/18305560/122237491-c0801300-ce95-11eb-83f8-1f9bfda6191c.png)

**Comment by ithallufernando** [comment]
> Olá @ithallufernando, tudo bem?
> Pelo que vi na mensagem, está ocorrendo uma exceção ao tentar comparar tipos de dados diferentes. Não era para acontecer! Tentei replicar o erro na minha máquina, porém o código rodou normalmente. Tente realizar o passo a passo do link a seguir:
> [Passo a passo](https://github.com/Mekylei-Belchior/lotofacil/issues/2#issuecomment-830655217)
> 
> ![tela-power_shell](https://user-images.githubusercontent.com/18305560/122237489-bf4ee600-ce95-11eb-86a6-187a36100438.png)
> 
> ![tela-pycharm](https://user-images.githubusercontent.com/18305560/122237491-c0801300-ce95-11eb-83f8-1f9bfda6191c.png)

Boa tarde @Mekylei-Belchior !

Consegui executar aqui, refiz o processo como me passou e ocorreu tudo certo.
Muito Obrigado.

**Comment by ithallufernando** [comment]
[base_dados.xlsx](https://github.com/Mekylei-Belchior/lotofacil/files/6664252/base_dados.xlsx)
Também atualizei a base de dados para o último sorteio 15/06/2021.
