### ISSUE TITLE
Atualizaçao Automatica com o Arquivo de Resultado da Caixa

### ISSUE THREAD

**Issue by CyowSepek** [Mekylei-Belchior/lotofacil#2]
Boa Noite amigo, muito legal sua iniciativa, gostaria de contribuir com o projeto se achar interessando pode colocar esse codigo para que possa automatizar a captura dos resultados dos concursos de forma automatica com os dados sendo atualizado pela caixa.

Ai teria que adaptar para poder criar as colunas que utiliza para o controle dos ciclos.

`import json 
import requests 
import pandas              as pd
import numpy               as np
import matplotlib.pyplot   as plt
import seaborn             as sns
import missingno           as msno
import zipfile
import math as math
from pylab import rcParams
from bs4 import BeautifulSoup
from random import randint
import lxml

url = 'http://www1.caixa.gov.br/loterias/_arquivos/loterias/D_lotfac.zip'
target_path = 'D_lotfac.zip'
response = requests.get(url, stream=True)

handle = open(target_path, "wb")
for chunk in response.iter_content(chunk_size=512):
    if chunk:  # filter out keep-alive new chunks
        handle.write(chunk)
handle.close()
with zipfile.ZipFile(target_path) as zf:
    zf.extractall()

fileHtml = 'd_lotfac.htm'

f = open(fileHtml, 'r', encoding='latin-1') 
table=f.read()

soup = BeautifulSoup(table, 'html.parser')
table = soup.find(name='table')

table_str = str(table)
df = pd.read_html(table_str)[0]

df.shape
df.dtypes

df['data_sorteio_conv'] = df.iloc[:,1]
df.data_sorteio_conv = pd.to_datetime(df.data_sorteio_conv)

df['day']   = df.data_sorteio_conv.dt.day
df['month'] = df.data_sorteio_conv.dt.month 
df['year']  = df.data_sorteio_conv.dt.year

df_ganhadores = df[:]

df_ganhadores.head()

# Visão geral do dataframe
msno.matrix(df=df.iloc[:,0:df.shape[1]], figsize=(20, 5), color=(0.42, 0.1, 0.05))

# Removendo valores nulos 
df = df.dropna(subset=['Concurso'])
msno.matrix(df=df.iloc[:,0:df.shape[1]], figsize=(20, 5), color=(0.42, 0.1, 0.05))

# Removendo colunas Cidade e UF
df = df.drop(['Cidade', 'UF'], axis=1)
msno.matrix(df=df.iloc[:,0:df.shape[1]], figsize=(20, 5), color=(0.42, 0.1, 0.05))

# Ganhadores X Volume do Prêmio por Estado 

ax = df_ganhadores.groupby(['UF'])['Ganhadores_13_Números'].agg('sum').sort_values(ascending=False).plot(kind='bar', title='Ganhadores por Estado', figsize=(15,5), fontsize=12, legend=True, position=1, color='gray')
# df_ganhadores.groupby(['UF'])['Rateio_Sena'].agg('sum').sort_values(ascending=False).plot(kind='bar', ax=ax, secondary_y=True, legend=True, position=0, color='blue')

# Ganhadores X Mes
# Ganhadores X Volume do Prêmio por Estado 
df_ganhadores.groupby(['month'])['Ganhadores_15_Números'].agg('sum').plot(kind='bar', title='Ganhadores X Mês', fontsize=12, figsize=(15,5), legend=True, color='gray')

# Verificando se alguma vez as dezenas se repetiram na mesma ordem
df.groupby(['Bola1','Bola2', 'Bola3', 'Bola4', 'Bola5', 'Bola6','Bola7', 'Bola8', 'Bola9', 'Bola10', 'Bola11','Bola12', 'Bola13', 'Bola14', 'Bola15']).size().sort_values(ascending=False)

# As dezenas mais sorteadas em todos os jogos
dezenas = pd.DataFrame(df['Bola1'].tolist() + df['Bola2'].tolist() + df['Bola3'].tolist() + df['Bola4'].tolist() + df['Bola5'].tolist() + df['Bola6'].tolist() +df['Bola7'].tolist() + df['Bola8'].tolist() + df['Bola9'].tolist() + df['Bola10'].tolist() + df['Bola11'].tolist() + df['Bola12'].tolist() +
df['Bola13'].tolist() + df['Bola14'].tolist() + df['Bola15'].tolist(), columns=['numeros'])

dezenas['numeros'].value_counts().sort_values(ascending=True).plot(kind='barh', title='As quinze dezenas mais sorteadas em todos os jogos', figsize=(10,5), fontsize=12, legend=True, color='gray')

# Criando dataframe que vamos usar nos modelos 

df_clean = df
index = 0
anterior = ''
for concurso in df['Concurso']:
    if(concurso == anterior):
        df_clean = df_clean.drop(index)
    index += 1
    anterior = concurso

df_clean.shape

df_nn = df_clean[['Bola1','Bola2', 'Bola3', 'Bola4', 'Bola5', 'Bola6','Bola7', 'Bola8', 'Bola9', 'Bola10', 'Bola11','Bola12', 'Bola13', 'Bola14', 'Bola15', 'Ganhadores_15_Números']] 

# Deixando os nomes das coluna em minusculo
df_nn.columns = map(str.lower, df_nn.columns)

df_nn.head(15)

# Pode existir mais de um ganhador por jogo
df_nn[df_nn['ganhadores_15_números'] > 1].groupby('ganhadores_15_números')['ganhadores_15_números'].agg('count').plot(kind='bar',figsize=(10,5), color='gray', fontsize=12)

# Então tudo jogo que tiver um ou mais ganhadores deixamos como o numeoro 1
df_nn.loc[df_nn['ganhadores_15_números'] > 0, 'ganhadores_15_números'] = 1

df_nn['ganhadores_15_números'].value_counts().plot(kind='bar', figsize=(10,5), color='gray', fontsize=12)

## montando vetor concurso anterior para uso futuro - repetidas do anterior

concurso = []
counts = []
anterior = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
for index, row in df_nn.iterrows():
    concurso = []
    concurso.append(row['bola1'])
    concurso.append(row['bola2'])
    concurso.append(row['bola3'])
    concurso.append(row['bola4'])
    concurso.append(row['bola5'])
    concurso.append(row['bola6'])
    concurso.append(row['bola7'])
    concurso.append(row['bola8'])
    concurso.append(row['bola9'])
    concurso.append(row['bola10'])
    concurso.append(row['bola11'])
    concurso.append(row['bola12'])
    concurso.append(row['bola13'])
    concurso.append(row['bola14'])
    concurso.append(row['bola15'])
    count = 0
    for x in range(15):
        if(np.count_nonzero(concurso==anterior[x]) > 0):
            count += 1   
    anterior = concurso

ultimo_sorteio = sorted(anterior)

print("\n")
print("Resultado do Ultimo Concurso: {0} -> Dezenas: {1}".format(df_nn.shape[0], ultimo_sorteio))
print("\n")`

**Comment by Mekylei-Belchior** [comment]
Olá @CyowSepek, tudo bem? Fico contente que tenha gostado do projeto e queira contribuir. Você chegou a ver o código do arquivo "scrapping_resultados.py", (lotofacil/dados/scrapping_resultados.py)?  Ele já faz a atualização dos sorteios. Não seria este o mesmo resultado?

Acredito que seria interessante adaptá-lo para fazer a análise dos ciclos das dezenas e assim descartar a análise via arquivo do Excel. O que acha?

**Comment by moura579** [comment]
Bom dia Mekylei-Belchior e @CyowSepek, preciso da ajuda de vocês, baixei o código mas estou com dificuldades para poder rodar. baixei os pacotes e dependências e atualizei tudo, eu uso o POP OS, porem quando dou o comando para rodar o código aparece a mensagem 

clientesservicos@pop-os:~$ cd lotofacil/
clientesservicos@pop-os:~/lotofacil$ python3 jogar.py
Instrução ilegal (imagem do núcleo gravada)
clientesservicos@pop-os:~/lotofacil$

Poderia me ajudar por gentileza? Não saco muito de linux, mas creio que com a ajuda de vocês vou conseguir.
muito obrigado e desculpa por incomodar vocês.

**Comment by Mekylei-Belchior** [comment]
> Bom dia Mekylei-Belchior e @CyowSepek, preciso da ajuda de vocês, baixei o código mas estou com dificuldades para poder rodar. baixei os pacotes e dependências e atualizei tudo, eu uso o POP OS, porem quando dou o comando para rodar o código aparece a mensagem
> 
> clientesservicos@pop-os:~$ cd lotofacil/ clientesservicos@pop-os:~/lotofacil$ python3 jogar.py
> Instrução ilegal (imagem do núcleo gravada)
> clientesservicos@pop-os:~/lotofacil$
> 
> Poderia me ajudar por gentileza? Não saco muito de linux, mas creio que com a ajuda de vocês vou conseguir.
> muito obrigado e desculpa por incomodar vocês.

Bom tarde @moura579, tudo bem?

Peço desculpa pela demora no retorno. Somente tive tempo de dar uma olhada em sua mensagem agora. Então, o código roda em qualquer SO, salvo que tenha instalado o interpretador Python e as dependências necessárias. Pelo que observei, você baixou os arquivos para a sua máquina ou fez um "clone" do repositório e está tentando rodá-lo, certo? Sugiro fazer as seguintes etapas:

Ob.: Os comandos abaixo foram realizados no Windows via Power Shell. Dependendo do seu SO, eles podem necessitar de adaptações! Lembrando que o diretório raiz fica a seu critério (Desktop, Meus Documentos, etc.). 

1. Instalar o interpretador do Python em sua máquina, o seja, o Python (Versão do projeto -  Python 3 (v3.8.2));
2. Após instalado o interpretador, atualize o PIP (gerenciador de pacotes): `python -m pip install --upgrade pip`;
3. Crie um ambiente virtual para o projeto: `python -m venv lotofacil` ("lotofacil" será o nome do diretório do ambiente virtual, ao qual você pode escolher outro). Ao criar o ambiente virtual, você estará separando as parametrizações do projeto de outras alterações que possam ter no ambiente externo. Basicamente, você irá instalar neste ambiente somente as dependências que o projeto necessita para ser rodado;
4. Copie para dentro do diretório do ambiente virtual as pastas do projeto (analises, base, calculos, combinacoes, dados, modelo, processamento e sorteios) e os arquivos ("requirements.txt" e "jogar.py");
5. Execute o ambiente virtual: dentro do diretório do ambiente virtual, no meu caso ".\lotofacil", execute o comando para ativá-lo: `.\Scripts\Activate.ps1` deverá aparecer em "verde" o nome do diretório do ambiente, ao qual confirma que ele foi ativado. Para desativar o ambiente é só executar o comando `deactivate`.
6. Após ativar o ambiente virtual, é hora de instalar as principais dependências (pacotes) que o projeto utiliza. Para isso, você vai utilizar o PIP e o arquivo "requirements.txt": dentro do diretório do ambiente virtual, no meu caso ".\lotofacil", execute o comando `pip install -r requirements.txt`. Esse comando irá instalar os pacotes conforme a relação contida no arquivo.
7. Agora é preciso instalar mais dois pacote (TensorFlow e o XRLD ): `pip install tensorflow, xlrd==1.2.0`;
8. Também se faz necessário gerar um novo arquivo de todas as combinações possíveis. Acesse a pasta "combinacoes", e delete o arquivo "combinacoes.csv". Já faz um tempo que não mexo com esse projeto e lembro de ter upado esse CSV para o GitHub, contudo, ao tentar rodar a aplicação, acusou um erro. Por isso, ao gerar um novo arquivo o problema será resolvido. Assim, execute o comando:  `python .\dados\gerar_combinacoes.py`;
9. Por fim, é só rodar: `python .\jogar.py`

Baixei o projeto para o meu notebook e rodou normalmente com as mesmas etapas descritas acima. Acredito que irá funcionar na sua máquina também!

Vale lembrar que a análise de combinações no arquivo Excel é feita manualmente e precisa ser atualizada a cada sorteio. Fiquei sem tempo para implementar a automação desta parte. 

Outra coisa, fiz esse projeto com a finalidade de aprimoramento de conhecimento e estudo de Redes Neurais e não para fins financeiros. Utilize com bastante cautela, pois, não existe nenhuma evidência que o projeto possa trazer ganhos financeiros, ok? Qualquer prejuízo financeiro, entre outros, é de sua inteira responsabilidade!

No mais, espero que lhe ajude de alguma forma. Fique a vontade para realizar nova implementações e/ou reajustes!

**Comment by moura579** [comment]
Boa tarde Mekylei-Belchior, sou muito grato pela sua atenção. Vou fazer tudo que você me falou para vê se consigo. Muito obrigado meu amigo!

Enviado do Yahoo Mail no Android 
 
  Em sáb, 1 1e mai 1e 2021 às 13:07, ***@***.***> escreveu:   



Bom dia Mekylei-Belchior e @CyowSepek, preciso da ajuda de vocês, baixei o código mas estou com dificuldades para poder rodar. baixei os pacotes e dependências e atualizei tudo, eu uso o POP OS, porem quando dou o comando para rodar o código aparece a mensagem

***@***.***:/lotofacil$ python3 jogar.py
Instrução ilegal (imagem do núcleo gravada)
***@***.***:~/lotofacil$

Poderia me ajudar por gentileza? Não saco muito de linux, mas creio que com a ajuda de vocês vou conseguir.
muito obrigado e desculpa por incomodar vocês.


Bom tarde @moura579, tudo bem?

Peço desculpa pela demora no retorno. Somente tive tempo de dar uma olhada em sua mensagem agora. Então, o código roda em qualquer SO, salvo que tenha instalado o interpretador Python e as dependências necessárias. Pelo que observei, você baixou os arquivos para a sua máquina ou fez um "clone" do repositório e está tentando rodá-lo, certo? Sugiro fazer as seguintes etapas:

Ob.: Os comandos abaixo foram realizados no Windows via Power Shell. Dependendo do seu SO, eles podem necessitar de adaptações! Lembrando que o diretório raiz fica a seu critério (Desktop, Meus Documentos, etc.).
   
   - Instalar o interpretador do Python em sua máquina, o seja, o Python (Versão do projeto - Python 3 (v3.8.2));
   - Após instalado o interpretador, atualize o PIP (gerenciador de pacotes): python -m pip install --upgrade pip;
   - Crie um ambiente virtual para o projeto: python -m venv lotofacil ("lotofacil" será o nome do diretório do ambiente virtual, ao qual você pode escolher outro). Ao criar o ambiente virtual, você estará separando as parametrizações do projeto de outras alterações que possam ter no ambiente externo. Basicamente, você irá instalar neste ambiente somente as dependências que o projeto necessita para ser rodado;
   - Copie para dentro do diretório do ambiente virtual as pastas do projeto (analises, base, calculos, combinacoes, dados, modelo, processamento e sorteios) e os arquivos ("requirements.txt" e "jogar.py");
   - Execute o ambiente virtual: dentro do diretório do ambiente virtual, no meu caso ".\lotofacil", execute o comando para ativá-lo: .\Scripts\Activate.ps1 deverá aparecer em "verde" o nome do diretório do ambiente, ao qual confirma que ele foi ativado. Para desativar o ambiente é só executar o comando deactivate.
   - Após ativar o ambiente virtual, é hora de instalar as principais dependências (pacotes) que o projeto utiliza. Para isso, você vai utilizar o PIP e o arquivo "requirements.txt": dentro do diretório do ambiente virtual, no meu caso ".\lotofacil", execute o comando pip install -r requirements.txt. Esse comando irá instalar os pacotes conforme a relação contida no arquivo.
   - Agora é preciso instalar mais dois pacote (TensorFlow e o XRLD ): pip install tensorflow, xlrd==1.2.0;
   - Também se faz necessário gerar um novo arquivo de todas as combinações possíveis. Acesse a pasta "combinacoes", e delete o arquivo "combinacoes.csv". Já faz um tempo que não mexo com esse projeto e lembro de ter upado esse CSV para o GitHub, contudo, ao tentar rodar a aplicação, acusou um erro. Por isso, ao gerar um novo arquivo o problema será resolvido. Assim, execute o comando: python .\dados\gerar_combinacoes.py;
   - Por fim, é só rodar: python .\jogar.py

Baixei o projeto para o meu notebook e rodou normalmente com as mesmas etapas descritas acima. Acredito que irá funcionar na sua máquina também!

Vale lembrar que a análise de combinações no arquivo Excel é feita manualmente e precisa ser atualizada a cada sorteio. Fiquei sem tempo para implementar a automação desta parte.

Outra coisa, fiz esse projeto com a finalidade de aprimoramento de conhecimento e estudo de Redes Neurais e não para fins financeiros. Utilize com bastante cautela, pois, não existe nenhuma evidência que o projeto possa trazer ganhos financeiros, ok? Qualquer prejuízo financeiro, entre outros, é de sua inteira responsabilidade!

No mais, espero que lhe ajude de alguma forma. Fique a vontade para realizar nova implementações e/ou reajustes!
